name: Deploy Solution to Dev Environment CMS

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 🧩 Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 🧩 Step 2: Setup Node.js (SPFx requires Node 18 or 20)
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: 'npm'

      # 🧩 Step 3: Install Gulp CLI globally
      - name: Install Gulp CLI
        run: npm install --global gulp-cli

      # 🧩 Step 4: Install dependencies
      - name: Install project dependencies
        run: npm ci

      # 🧩 Step 5: Bundle and package SPFx solution
      - name: Bundle & Package solution
        run: |
          gulp bundle --ship
          gulp package-solution --ship

      # 🧩 Step 6: Verify output file path (debug helper)
      - name: Debug solution path
        run: ls -R sharepoint/solution

      # 🧩 Step 7: Login to Microsoft 365 using certificate-based auth
      - name: CLI for Microsoft 365 Login
        uses: pnp/action-cli-login@v2
        with:
          APP_ID: ${{ secrets.APP_ID }}
          TENANT: ${{ secrets.TENANT_ID }}
          CERTIFICATE_ENCODED: ${{ secrets.CERTIFICATE_ENCODED }}
          CERTIFICATE_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}

      # 🧩 Step 8: Deploy to Dev Site Collection App Catalog
      - name: Deploy SPFx app to Dev site collection
        id: devDeploy
        uses: pnp/action-cli-deploy@v4
        with:
          APP_FILE_PATH: sharepoint/solution/cms.sppkg
          SKIP_FEATURE_DEPLOYMENT: true
          OVERWRITE: true
          SCOPE: sitecollection
          SITE_COLLECTION_URL: https://credentinfotec.sharepoint.com/sites/IntranetPortal-Dev

      # 🧩 Step 9: Confirm Deployment
      - name: Deployment Status
        run: echo "✅ SPFx App deployed successfully to DEV site!"
